### ISSUE TITLE
[Question] Networking and access to kind via Kubectl

### ISSUE THREAD

**Issue by emirot** [kind-ci/examples#28]
Hi there,

I would love to use kind, my use case would be to test helm charts against different version of k8s versions(Kind nodes) to make sure that the api versions used in my k8s manifest will still work with newer version of K8s.

Unfortunately, I'm a bit stuck right now on accessing the kind cluster using kubectl.

I'm getting``` Unable to connect to the server: dial tcp: lookup docker on 10.37.36.27:53: no such host```
I've seen that you are patching kubeconfig in the examples https://github.com/kind-ci/examples/blob/master/.gitlab-ci.yml#L18 
Should I do the same if so what should it be? My environment is an EC2 instance running docker gitlab executor and this will be in a docker (docker stable) image as in https://github.com/kind-ci/examples/blob/master/.gitlab-ci.yml#L1

**Comment by tao12345666333** [comment]
1. you need to set your docker executor as **privileged mode**, then it can using `service` feature to run `docker:dind`, like this: https://github.com/kind-ci/examples/blob/643a731a116447acfa88bf0d2ac2f895123f237e/.gitlab-ci.yml#L5-L6.   ref: https://docs.gitlab.com/runner/executors/docker.html#use-docker-in-docker-with-privileged-mode

2. if your `service` can works. GitLab runner will automatically set your build container's hosts records (`/etc/hosts` file).

3. Docker daemon supports connection over TLS. you need to set up accordingly.  ref: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
