### ISSUE TITLE
List of CI/CD systems integrations integrated with kind

### ISSUE THREAD

**Issue by aojea** [kind-ci/examples#3]
A `kind` user left a list of nice to have CI integrations

https://github.com/kubernetes-sigs/kind/issues/509#issuecomment-490998733

adding it here so we can track it

- [x] - CircleCI #5 
- [x] - TravisCI #4 
- [ ] - BuildKite
- [x] - Prow https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/kind
- [x] - Gitlab
- [ ] - Concourse
- [x] - Drone
- [ ] - GCB
- [ ] - Codeship https://github.com/kubernetes-sigs/kind/issues/523

**Comment by aojea** [comment]
hmmm 🤔 ping @munnerz @bentheelder, this repo has a lot of info already about this topic https://github.com/bsycorp/kind

**Comment by BenTheElder** [comment]
this is now tracked in the table in the README, let's open individual issues for CIs we don't know yet.
